### ISSUE TITLE
error

### ISSUE THREAD

**Issue by minskzxc** [vektort13/antidetect#2]
![vektor 2](https://user-images.githubusercontent.com/32418346/36168796-55f12290-110b-11e8-8f67-b2e8cf7339d4.PNG)
![vektor](https://user-images.githubusercontent.com/32418346/36168792-533277ca-110b-11e8-929d-dcf74a63f162.PNG)

**Comment by dfgioalpppaa** [comment]
`vboxmanage list vms`
?

**Comment by minskzxc** [comment]
"dfswsedr" {9e07c004-2060-40ca-b3a4-69b1433ae9e5}

**Comment by wauzzz** [comment]
VBoxManage setextradata "dfswsedr" VBoxInternal/TM/TSCMode RealTSCOffset
VBoxManage setextradata "dfswsedr" VBoxInternal/CPUM/SSE4.1 1
VBoxManage setextradata "dfswsedr" VBoxInternal/CPUM/SSE4.2 1

**Comment by minskzxc** [comment]
Thank you
