### ISSUE TITLE
Ошибки при запуске установленной программы

### ISSUE THREAD

**Issue by ristabalista** [vektort13/antidetect#3]
При запуске установленной по вебинару программы она ругается на ошибки в файлах 

- MSVCP100.dll  [http://prntscr.com/ig20e6](http://prntscr.com/ig20e6)

- MSVCR100.dll  [http://prntscr.com/ig20pu](http://prntscr.com/ig20pu)

- Qt5Core.dll      [http://prntscr.com/ig20yt](http://prntscr.com/ig20yt)

- Qt5Gui.dll        [http://prntscr.com/ig215i](http://prntscr.com/ig215i)

Как можно обойти эти ошибки и почему они возникли? Система на которой запускаю - Windows 10 Домашняя 64bit

UPD. Проблема решена,  Тестовый режим не включался без перезагрузки, перезагрузка и переустановка помогла

**Comment by minskzxc** [comment]
Ты сертификаты установил?

**Comment by ristabalista** [comment]
Я же написал, что устанавливал по вебинару - то есть сертификаты установил. Если их не установить то программа на десятку просто не встанет.
