### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ploobmz** [vektort13/antidetect#5]
![img1233](https://user-images.githubusercontent.com/36999088/36914629-97e2c1e2-1e56-11e8-84cf-b8e18e5509ea.png)
При установке выдает следующую ошибку.
П.с. сертификаты все установил

**Comment by artikonelove** [comment]
Возможно, у вас не правильно установлены сертификаты (для windows 7 особыми шаманскими методами это нужно делать). Я думаю, можно тут оставить ссылку, которую вектор вбрасывал для тех, у кого семерка: https://openssource.info/threads/voprosy-po-sborke-vbox-ot-vektort13-k-vebinaru.30845/page-4#post-310147 . Так же хотелось бы сделать это все в скринах, но я работаю с windows 8 и не совсем корректный гайд бы получился. Удачи в разрешении вашей проблемы!

**Comment by fr1zzer** [comment]
Такая же проблема и у меня только на win 10 x64

**Comment by ploobmz** [comment]
@artikonelove
Спасибо, сделал всё по инструкции! Помогло
